apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      containers:
        - name: jenkins
          #image: jenkins/jenkins:lts
          image: 192.168.154.128:5000/jenkins
          ports:
            - name: httpport
              containerPort: 8080
          resources:
            limits:
              memory: "2000Mi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
          - name: data
            mountPath: /var/jenkins_home
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: service-jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-server
  ports:
  - port: 8080
    nodePort: 30808
