apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadviser
spec:
  selector:
    matchLabels:
      app: cadviser
  template:
    metadata:
      labels:
        app: cadviser
    spec:
      nodeName: workstation
      containers:
      - name: cadviser
        #image: gcr.io/cadvisor/cadvisor:latest
        image: 192.168.154.128:5000/cadvisor
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1G"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "256Mi"  
        volumeMounts:
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: run
          mountPath: /var/run/
        - name: sys
          mountPath: /sys
          readOnly: true

      volumes:
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: run
        hostPath:
          path: /var/run/
      - name: sys
        hostPath:
          path: /sys
        


---
apiVersion: v1
kind: Service
metadata:
  name: service-cadviser
spec:
  type: NodePort
  selector:
    app: cadviser
  ports:
  - name: cad-port
    port: 8080
    targetPort: 8080
    nodePort: 30800
