apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-prometheus
data:
  alertmanager.yml: |
    route:
      receiver: 'slack'
    receivers:
    - name: 'slack'
      slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        username: "home_kubernetes"
        channel: "alerting"
        api_url: "Your API"

  alert.rules: |
    groups:
    - name: targets
      rules:
      - alert: monitor_service_down
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Monitor service"
          description: "Service {{ $labels.job }} is down"
      
      - alert: containerkilled
        expr: time() - container_last_seen > 10
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Container killed (instance {{ $labels.instance }})"
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
    - "alert.rules"
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets: ['alertmanagers-service.default.svc.cluster.local:9093']

    scrape_configs:
    - job_name: 'cadvisor'
      static_configs:
      - targets: ["192.168.88.143:30800"]
    - job_name: 'kube_metrics'
      static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
