apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-prometheus
data:
  alertmanager.yml: |
    route:
      receiver: 'slack'
    receivers:
    - name: 'slack'
      slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        username: "home_kubernetes"
        channel: "alerting"
        api_url: "Your API"

  alert.rules: |
    groups:
    - name: targets
      rules:
      - alert: monitor_service_down
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Monitor service"
          description: "Service {{ $labels.job }} is down"
      - alert: Pod restart
        expr: sum(kube_pod_container_status_restarts_total) by (pod) > 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "pod reset"
          description: "{{ $labels.pod }}"
      - alert: containerkilled
        expr: time() - container_last_seen > 10
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Container killed (instance {{ $labels.instance }})"
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: KubernetesNodeMemoryPressure
        expr: kube_node_status_condition{condition="MemoryPressure",status="true"} == 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Kubernetes Node memory pressure (instance {{ $labels.instance }})
          description: "Node {{ $labels.node }} has MemoryPressure condition\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: MysqlDown
        expr: mysql_up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: MySQL down (instance {{ $labels.instance }})
          description: "MySQL instance is down on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
    - "alert.rules"
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets: ['alertmanagers-service.default.svc.cluster.local:9093']

    scrape_configs:
    - job_name: 'cadvisor'
      static_configs:
      - targets: ["service-cadviser.default.svc.cluster.local:8080"]
    - job_name: 'kube_metrics'
      static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
