apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'cadvisor'
      static_configs:
              - targets: ["192.168.154.141:30800"]
